package edu.utm.bd.domain;

public class Cliente {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cliente.id_cliente
     *
     * @mbggenerated Wed Apr 25 18:29:14 CDT 2018
     */
    private Integer idCliente;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cliente.nombre
     *
     * @mbggenerated Wed Apr 25 18:29:14 CDT 2018
     */
    private String nombre;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cliente.apellido
     *
     * @mbggenerated Wed Apr 25 18:29:14 CDT 2018
     */
    private String apellido;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cliente.correo
     *
     * @mbggenerated Wed Apr 25 18:29:14 CDT 2018
     */
    private String correo;
    
    private Boolean estadoCliente;

  

	/**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cliente.id_cliente
     *
     * @return the value of cliente.id_cliente
     *
     * @mbggenerated Wed Apr 25 18:29:14 CDT 2018
     */
    public Integer getIdCliente() {
        return idCliente;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cliente.id_cliente
     *
     * @param idCliente the value for cliente.id_cliente
     *
     * @mbggenerated Wed Apr 25 18:29:14 CDT 2018
     */
    public void setIdCliente(Integer idCliente) {
        this.idCliente = idCliente;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cliente.nombre
     *
     * @return the value of cliente.nombre
     *
     * @mbggenerated Wed Apr 25 18:29:14 CDT 2018
     */
    public String getNombre() {
        return nombre;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cliente.nombre
     *
     * @param nombre the value for cliente.nombre
     *
     * @mbggenerated Wed Apr 25 18:29:14 CDT 2018
     */
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cliente.apellido
     *
     * @return the value of cliente.apellido
     *
     * @mbggenerated Wed Apr 25 18:29:14 CDT 2018
     */
    public String getApellido() {
        return apellido;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cliente.apellido
     *
     * @param apellido the value for cliente.apellido
     *
     * @mbggenerated Wed Apr 25 18:29:14 CDT 2018
     */
    public void setApellido(String apellido) {
        this.apellido = apellido;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cliente.correo
     *
     * @return the value of cliente.correo
     *
     * @mbggenerated Wed Apr 25 18:29:14 CDT 2018
     */
    public String getCorreo() {
        return correo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cliente.correo
     *
     * @param correo the value for cliente.correo
     *
     * @mbggenerated Wed Apr 25 18:29:14 CDT 2018
     */
    public void setCorreo(String correo) {
        this.correo = correo;
    }
    
    public Boolean getEstadoCliente() {
  		return estadoCliente;
  	}

  	public void setEstadoCliente(Boolean estadoCliente) {
  		this.estadoCliente = estadoCliente;
  	}
}