package edu.utm.bd.domain;

public class Detalle {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column detalle.id_detalle
     *
     * @mbggenerated Wed Apr 25 18:29:14 CDT 2018
     */
    private Integer idDetalle;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column detalle.id_producto
     *
     * @mbggenerated Wed Apr 25 18:29:14 CDT 2018
     */
    private Integer idProducto;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column detalle.cantidad
     *
     * @mbggenerated Wed Apr 25 18:29:14 CDT 2018
     */
    private Integer cantidad;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column detalle.monto
     *
     * @mbggenerated Wed Apr 25 18:29:14 CDT 2018
     */
    private Long monto;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column detalle.id_factura
     *
     * @mbggenerated Wed Apr 25 18:29:14 CDT 2018
     */
    private Integer idFactura;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column detalle.id_detalle
     *
     * @return the value of detalle.id_detalle
     *
     * @mbggenerated Wed Apr 25 18:29:14 CDT 2018
     */
    public Integer getIdDetalle() {
        return idDetalle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column detalle.id_detalle
     *
     * @param idDetalle the value for detalle.id_detalle
     *
     * @mbggenerated Wed Apr 25 18:29:14 CDT 2018
     */
    public void setIdDetalle(Integer idDetalle) {
        this.idDetalle = idDetalle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column detalle.id_producto
     *
     * @return the value of detalle.id_producto
     *
     * @mbggenerated Wed Apr 25 18:29:14 CDT 2018
     */
    public Integer getIdProducto() {
        return idProducto;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column detalle.id_producto
     *
     * @param idProducto the value for detalle.id_producto
     *
     * @mbggenerated Wed Apr 25 18:29:14 CDT 2018
     */
    public void setIdProducto(Integer idProducto) {
        this.idProducto = idProducto;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column detalle.cantidad
     *
     * @return the value of detalle.cantidad
     *
     * @mbggenerated Wed Apr 25 18:29:14 CDT 2018
     */
    public Integer getCantidad() {
        return cantidad;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column detalle.cantidad
     *
     * @param cantidad the value for detalle.cantidad
     *
     * @mbggenerated Wed Apr 25 18:29:14 CDT 2018
     */
    public void setCantidad(Integer cantidad) {
        this.cantidad = cantidad;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column detalle.monto
     *
     * @return the value of detalle.monto
     *
     * @mbggenerated Wed Apr 25 18:29:14 CDT 2018
     */
    public Long getMonto() {
        return monto;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column detalle.monto
     *
     * @param monto the value for detalle.monto
     *
     * @mbggenerated Wed Apr 25 18:29:14 CDT 2018
     */
    public void setMonto(Long monto) {
        this.monto = monto;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column detalle.id_factura
     *
     * @return the value of detalle.id_factura
     *
     * @mbggenerated Wed Apr 25 18:29:14 CDT 2018
     */
    public Integer getIdFactura() {
        return idFactura;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column detalle.id_factura
     *
     * @param idFactura the value for detalle.id_factura
     *
     * @mbggenerated Wed Apr 25 18:29:14 CDT 2018
     */
    public void setIdFactura(Integer idFactura) {
        this.idFactura = idFactura;
    }
}