package edu.utm.bd.domain;

import java.util.Date;

public class Factura {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column factura.id_factura
     *
     * @mbggenerated Wed Apr 25 18:29:14 CDT 2018
     */
    private Integer idFactura;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column factura.id_cliente
     *
     * @mbggenerated Wed Apr 25 18:29:14 CDT 2018
     */
    private Integer idCliente;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column factura.id_vendedor
     *
     * @mbggenerated Wed Apr 25 18:29:14 CDT 2018
     */
    private Integer idVendedor;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column factura.fecha
     *
     * @mbggenerated Wed Apr 25 18:29:14 CDT 2018
     */
    private Date fecha;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column factura.monto_total
     *
     * @mbggenerated Wed Apr 25 18:29:14 CDT 2018
     */
    private Long montoTotal;
    
    private Cliente  clienteDatos;
	private Vendedor vendedorDatos;
    private Producto productoDatos;
    private Detalle  detalleDatos;
    private String Client;
    private String Vendedo;
    
    
    
    
    public String getVendedo() {
		return Vendedo;
	}

	public void setVendedo(String vendedo) {
		Vendedo = vendedo;
	}

	public String getClient() {
		return Client;
	}

	public void setClient(String client) {
		Client = client;
	}

	public Detalle getDetalleDatos() {
		return detalleDatos;
	}

	public void setDetalleDatos(Detalle detalleDatos) {
		this.detalleDatos = detalleDatos;
	}

	public Producto getProductoDatos() {
		return productoDatos;
	}

	public void setProductoDatos(Producto productoDatos) {
		this.productoDatos = productoDatos;
	}

	public Vendedor getVendedorDatos() {
		return vendedorDatos;
	}

	public void setVendedorDatos(Vendedor vendedorDatos) {
		this.vendedorDatos = vendedorDatos;
	}

	public Cliente getClienteDatos() {
		return clienteDatos;
	}

	public void setClienteDatos(Cliente clienteDatos) {
		this.clienteDatos = clienteDatos;
	}

	/**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column factura.id_factura
     *
     * @return the value of factura.id_factura
     *
     * @mbggenerated Wed Apr 25 18:29:14 CDT 2018
     */
    public Integer getIdFactura() {
        return idFactura;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column factura.id_factura
     *
     * @param idFactura the value for factura.id_factura
     *
     * @mbggenerated Wed Apr 25 18:29:14 CDT 2018
     */
    public void setIdFactura(Integer idFactura) {
        this.idFactura = idFactura;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column factura.id_cliente
     *
     * @return the value of factura.id_cliente
     *
     * @mbggenerated Wed Apr 25 18:29:14 CDT 2018
     */
    public Integer getIdCliente() {
        return idCliente;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column factura.id_cliente
     *
     * @param idCliente the value for factura.id_cliente
     *
     * @mbggenerated Wed Apr 25 18:29:14 CDT 2018
     */
    public void setIdCliente(Integer idCliente) {
        this.idCliente = idCliente;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column factura.id_vendedor
     *
     * @return the value of factura.id_vendedor
     *
     * @mbggenerated Wed Apr 25 18:29:14 CDT 2018
     */
    public Integer getIdVendedor() {
        return idVendedor;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column factura.id_vendedor
     *
     * @param idVendedor the value for factura.id_vendedor
     *
     * @mbggenerated Wed Apr 25 18:29:14 CDT 2018
     */
    public void setIdVendedor(Integer idVendedor) {
        this.idVendedor = idVendedor;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column factura.fecha
     *
     * @return the value of factura.fecha
     *
     * @mbggenerated Wed Apr 25 18:29:14 CDT 2018
     */
    public Date getFecha() {
        return fecha;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column factura.fecha
     *
     * @param fecha the value for factura.fecha
     *
     * @mbggenerated Wed Apr 25 18:29:14 CDT 2018
     */
    public void setFecha(Date fecha) {
        this.fecha = fecha;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column factura.monto_total
     *
     * @return the value of factura.monto_total
     *
     * @mbggenerated Wed Apr 25 18:29:14 CDT 2018
     */
    public Long getMontoTotal() {
        return montoTotal;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column factura.monto_total
     *
     * @param montoTotal the value for factura.monto_total
     *
     * @mbggenerated Wed Apr 25 18:29:14 CDT 2018
     */
    public void setMontoTotal(Long montoTotal) {
        this.montoTotal = montoTotal;
    }
}