package edu.utm.bd.domain;

public class Vendedor {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vendedor.id_vendedor
     *
     * @mbggenerated Wed Apr 25 18:29:14 CDT 2018
     */
    private Integer idVendedor;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vendedor.nombre
     *
     * @mbggenerated Wed Apr 25 18:29:14 CDT 2018
     */
    private String nombre;

    
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vendedor.apellido
     *
     * @mbggenerated Wed Apr 25 18:29:14 CDT 2018
     */
    private String apellido;
    
    private String username;
    private Boolean estadoVendedor;
   


	/**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vendedor.contrase�a
     *
     * @mbggenerated Wed Apr 25 18:29:14 CDT 2018
     */
    private String contrasena;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vendedor.correo
     *
     * @mbggenerated Wed Apr 25 18:29:14 CDT 2018
     */
    private String correo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vendedor.administrador
     *
     * @mbggenerated Wed Apr 25 18:29:14 CDT 2018
     */
    private Boolean administrador;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vendedor.id_vendedor
     *
     * @return the value of vendedor.id_vendedor
     *
     * @mbggenerated Wed Apr 25 18:29:14 CDT 2018
     */
    public Integer getIdVendedor() {
        return idVendedor;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vendedor.id_vendedor
     *
     * @param idVendedor the value for vendedor.id_vendedor
     *
     * @mbggenerated Wed Apr 25 18:29:14 CDT 2018
     */
    public void setIdVendedor(Integer idVendedor) {
        this.idVendedor = idVendedor;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vendedor.nombre
     *
     * @return the value of vendedor.nombre
     *
     * @mbggenerated Wed Apr 25 18:29:14 CDT 2018
     */
    public String getNombre() {
        return nombre;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vendedor.nombre
     *
     * @param nombre the value for vendedor.nombre
     *
     * @mbggenerated Wed Apr 25 18:29:14 CDT 2018
     */
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vendedor.apellido
     *
     * @return the value of vendedor.apellido
     *
     * @mbggenerated Wed Apr 25 18:29:14 CDT 2018
     */
    public String getApellido() {
        return apellido;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vendedor.apellido
     *
     * @param apellido the value for vendedor.apellido
     *
     * @mbggenerated Wed Apr 25 18:29:14 CDT 2018
     */
    public void setApellido(String apellido) {
        this.apellido = apellido;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vendedor.contrase�a
     *
     * @return the value of vendedor.contrase�a
     *
     * @mbggenerated Wed Apr 25 18:29:14 CDT 2018
     */
    public String getUsername() {
		return username;
	}

    
	public void setUsername(String username) {
		this.username = username;
	}
	
    public String getContrasena() {
        return contrasena;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vendedor.contrase�a
     *
     * @param contrase�a the value for vendedor.contrase�a
     *
     * @mbggenerated Wed Apr 25 18:29:14 CDT 2018
     */
    public void setContrasena(String contrasena) {
        this.contrasena = contrasena;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vendedor.correo
     *
     * @return the value of vendedor.correo
     *
     * @mbggenerated Wed Apr 25 18:29:14 CDT 2018
     */
    public String getCorreo() {
        return correo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vendedor.correo
     *
     * @param correo the value for vendedor.correo
     *
     * @mbggenerated Wed Apr 25 18:29:14 CDT 2018
     */
    public void setCorreo(String correo) {
        this.correo = correo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vendedor.administrador
     *
     * @return the value of vendedor.administrador
     *
     * @mbggenerated Wed Apr 25 18:29:14 CDT 2018
     */
    public Boolean getAdministrador() {
        return administrador;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vendedor.administrador
     *
     * @param administrador the value for vendedor.administrador
     *
     * @mbggenerated Wed Apr 25 18:29:14 CDT 2018
     */
    public void setAdministrador(Boolean administrador) {
        this.administrador = administrador;
    }

	public Boolean getEstadoVendedor() {
		return estadoVendedor;
	}

	public void setEstadoVendedor(Boolean estadoVendedor) {
		this.estadoVendedor = estadoVendedor;
	}
    


}